var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-state borders
		'lakesColor':'#ACE9FC', // lakes color
		'namesColor': '#333', //color of short names
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ALABAMA', //state hover content
		'url':'/map/al', //Goto URL
		'target':'new_window', //open link in new window:new_window, open in current window:new_window, or none for nothing.
		'upColor':'#84C2FF', //state's color when page loads
		'overColor':'#F5F5F5', //state's color when mouse hover
		'downColor': '#d3cfcf',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'ALASKA',
		'url':'/map/ak',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_3':{
		'hover': 'ARIZONA',
		'url':'/map/az',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_4':{
		'hover': 'ARKANSAS',
		'url':'/map/ar',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_5':{
		'hover': 'CALIFORNIA',
		'url':'/map/ca',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_6':{
		'hover': 'COLORADO',
		'url':'/map/co',
		'target':'new_window',
		'upColor':'#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_7':{
		'hover': 'CONNECTICUT',
		'url':'/map/ct',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_8':{
		'hover': 'DELAWARE',
		'url':'/map/de',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_9':{
		'hover': 'FLORIDA',
		'url':'/map/fl',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_10':{
		'hover': 'GEORGIA',
		'url':'/map/ga',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_11':{
		'hover': 'HAWAII',
		'url':'/map/hi',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_12':{
		'hover': 'IDAHO',
		'url':'/map/id',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_13':{
		'hover': 'ILLINOIS',
		'url':'/map/il',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_14':{
		'hover': 'INDIANA',
		'url':'/map/in',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_15':{
		'hover': 'IOWA',
		'url':'/map/ia',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_16':{
		'hover': 'KANSAS',
		'url':'/map/ks',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_17':{
		'hover': 'KENTUCKY',
		'url':'/map/ky',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_18':{
		'hover': 'LOUISIANA',
		'url':'/map/la',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_19':{
		'hover': 'MAINE',
		'url':'/map/me',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_20':{
		'hover': 'MARYLAND',
		'url':'/map/md',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_21':{
		'hover': 'MASSACHUSETTS',
		'url':'/map/ma',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_22':{
		'hover': 'MICHIGAN',
		'url':'/map/mi',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_23':{
		'hover': 'MINNESOTA',
		'url':'/map/mn',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_24':{
		'hover': 'MISSISSIPPI',
		'url':'/map/ms',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_25':{
		'hover': 'MISSOURI',
		'url':'/map/mo',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_26':{
		'hover': 'MONTANA',
		'url':'/map/mt',
		'target':'new_window',
		'upColor': '#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_27':{
		'hover': 'NEBRASKA',
		'url':'/map/ne',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_28':{
		'hover': 'NEVADA',
		'url':'/map/nv',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_29':{
		'hover': 'NEW HAMPSHIRE',
		'url':'/map/nh',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_30':{
		'hover': 'NEW JERSEY',
		'url': '/map/nj',
		'target': 'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_31':{
		'hover': 'NEW MEXICO',
		'url': '/map/nm',
		'target': 'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_32':{
		'hover': 'NEW YORK',
		'url': '/map/ny',
		'target': 'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_33':{
		'hover': 'NORTH CAROLINA',
		'url': '/map/nc',
		'target': 'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_34':{
		'hover': 'NORTH DAKOTA',
		'url':'/map/nd',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_35':{
		'hover': 'OHIO',
		'url': '/map/oh',
		'target': 'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_36':{
		'hover': 'OKLAHOMA',
		'url':'/map/ok',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_37':{
		'hover': 'OREGON',
		'url': '/map/or',
		'target': 'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_38':{
		'hover': 'PENNSYLVANIA',
		'url':'/map/pa',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_39':{
		'hover': 'RHODE ISLAND',
		'url': '/map/ri',
		'target': 'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_40':{
		'hover': 'SOUTH CAROLINA',
		'url':'/map/sc',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_41':{
		'hover': 'SOUTH DAKOTA',
		'url':'/map/sd',
		'target':'new_window',
		'upColor': '#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_42':{
		'hover': 'TENNESSEE',
		'url':'/map/tn',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_43':{
	    'hover': 'TEXAS',
		'url':'/map/tx',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_44':{
		'hover': 'UTAH',
		'url':'/map/ut',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_45':{
		'hover': 'VERMONT',
		'url':'/map/vt',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_46':{
		'hover': 'VIRGINIA',
		'url':'/map/va',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_47':{
		'hover': 'WASHINGTON',
		'url':'/map/wa',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_48':{
		'hover': 'WEST VIRGINIA',
		'url':'/map/wv',
		'target':'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_49':{
		'hover': 'WISCONSIN',
		'url':'/map/wi',
		'target':'new_window',
		'upColor': '#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_50':{
		'hover': 'WYOMING',
		'url':'/map/wy',
		'target':'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
'map_51':{
		'hover': 'PUERTO RICO',
		'url': '/map/pr',
		'target': 'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_52':{
		'hover': 'VIRGIN ISLANDS',
		'url': '/map/vi',
		'target': 'new_window',
		'upColor': '#FFEE88',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_53':{
		'hover': 'GUAM',
		'url': '/map/gu',
		'target': 'new_window',
		'upColor':'#84C2FF',
		'overColor':'#F5F5F5',
		 'downColor':'#d3cfcf',
		'enable':true,
	},
	'map_54': {
	    'hover': 'District of Columbia',
	    'url': '/map/dc',
	    'target': 'new_window',
	    'upColor': '#84C2FF',
	    'overColor': '#FFEE88',
	    'downColor': '#d3cfcf',
	    'enable': true,
	},
}
